name: Go

on:
  push:
    branches: ["main", "refactor/ui"]
  pull_request:
    branches: ["main", "refactor/ui"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install package
        run: |
          sudo apt-get update -y; sudo apt-get -y install libxi-dev libxinerama-dev libxcursor-dev libxrandr-dev libgl1-mesa-dev
        if: runner.os == 'Linux'

      - name: Get
        run: go get

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
